@startuml DiagLigne
'--------------------------------
' Parametres pour le dessin
'--------------------------------
hide circle
hide empty members
hide empty methods
'--------------------------------

class Ligne{ 

}
class Point  {


}

Ligne "0..*" -- "2" Point
@enduml