@startuml Titre
'--------------------------------
' Parametres pour le dessin
'--------------------------------
'--http://iut-blagnac.github.io/POO/TD3.html--
hide circle
hide empty members
hide empty methods
'--------------------------------

'4.2.1

'2.1.1. Énoncé
'Dans un établissement scolaire, on désire gérer la réservation 
'des salles de cours et du matériel pédagogique (ordinateur portable 
'et/ou vidéo-projecteur). Seuls les enseignants sont habilités à
' effectuer des réservations (sous réserve de disponibilité de la 
' salle ou du matériel). Le planning des salles peut quant à lui 
' être consulté par tout le monde (enseignants et étudiants). Par
'  contre, le récapitulatif horaire par enseignant (calculé à partir
'   du planning des salles) ne peut être consulté que par les enseignants.
'   nfin, il existe pour chaque formation un enseignant responsable qui
'    seul peut éditer le récapitulatif horaire pour l’ensemble de la
'     formation.'

'2.1.2. Question
'Modéliser cette situation par un diagramme de cas d’utilisation.

usecase (Réserver) as Reserver

usecase (Réserver salle) as SReserver
usecase (Réserver matériel) as MReserver

usecase (Consulter edt) as Consulter
usecase (Consulter récapitulatif) as CRecap
usecase (Éditer récapitulatif) as ERecap
usecase (Disponible?) as Dispo
actor Enseignant
actor Etudiant
actor Responsable

Enseignant -|> Etudiant
Responsable -|> Enseignant

Reserver --> SReserver
Reserver --> MReserver

SReserver --> Dispo
MReserver --> Dispo

Enseignant --> Reserver
Enseignant --> CRecap
Etudiant --> Consulter
Responsable --> ERecap

@enduml