@startuml Titre
'--------------------------------
' Parametres pour le dessin
'--------------------------------
'--http://iut-blagnac.github.io/POO/TD4.html--
hide circle
hide empty members
hide empty methods
'--------------------------------

'5.1.1


participant A as client 
participant B as caissier 


@enduml